### ISSUE TITLE
multi-level group headers..

### ISSUE THREAD

**Issue by dizzy0ny** [free-jqgrid/jqGrid#32]
There are two features i need for a task i am working on.  The first is an implementation of a tree view..which i think this fork's implementation meets: http://www.ok-soft-gmbh.com/jqGrid/OK/LocalAdjacencyTree.htm

The other a multi-level headers (including when in tree-view mode)...tony's version implements this, but i think it is a bit limiting (i.e.resizing is a bit buggy and can not easily hide columns client side).

I need to display about 2000 rows, but grouped in 3 levels using a  treeview down to about 30 nodes...so performance may be a bit of a concern.

**Comment by tonytomov** [comment]
Hello,

About the first feature. Did you have chance to look at the demo here: http://www.guriddo.net/demo/treegridjs/

**Comment by OlegKi** [comment]
Hello @dizzy0ny ,

I don't see any problem in implementation of your scenario in general. I personally never tested the combination of TreeGrid with Multi-Level headers before, but I did it after reading of your post. I don't know any problem in resizing of the grid. I'v found some small problems in [autoResizing](https://github.com/free-jqgrid/jqGrid/wiki/Auto-adjustment-of-the-width-of-column) only, but there are no problem in the resizing itself (resizing of column by drag and drop of resizing div which exist between the column headers). I fixed the problems in autoResizing just now. See [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/LocalAdjacencyTree-fa4.htm) which uses the latest sources from GitHub.

If you will find some problems in the implementation of your scenario or a bug in free jqGrid then you can post here the corresponding bug report with the demo which reproduces the problem. I fix bugs typically very quickly. Any common questions you can ask on the stackoverflow.

Best regards
Oleg

**Comment by dizzy0ny** [comment]
@tonytomov thanks, and no i did not see that demo, looks great. @OlegKi thanks much!  I will try these and report back.  Any possibility i can contact either of you via email to properly introduce myself and discuss further what the reqs are?

**Comment by tonytomov** [comment]
>Any possibility i can contact either of you via email to properly introduce myself and discuss further what the reqs are?
Sure
About the demo - you forgot to put the pager option in the grid options. Putting it it works. Editing work with tree grid. I recommend you to visit the docs here: http://www.trirand.com/jqgridwiki/doku.php?id=wiki:jqgriddocs in order to clarify some things

**Comment by OlegKi** [comment]
To @dizzy0ny : you need specify **which column** need be editable. You need include `editable: true` property in columns of `colModel` which need be editable. You can include `editable: true` inside of `cmTemplate` if you want that the value `editable: true` be default for all your columns. To add navigation bar you should add `pager: "#pager"` option, which will corresponds to `.jqGrid("navGrid", "#pager", ...`. It's unclear for me how "Add" operation should work in your case. By the way you can use [new style of options](https://github.com/free-jqgrid/jqGrid/wiki/New-style-of-usage-options-of-internal-methods), like `pager: true` and specifying `navOptions`, `searching`, `formEditing` and other as *the option of jqGrid*. As the result you will have the code like below
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>http://stackoverflow.com/q/27617764/315935</title>
    <meta name="author" content="Oleg Kiriljuk">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/redmond/jquery-ui.css">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="http://rawgit.com/free-jqgrid/jqGrid/master/css/ui.jqgrid.css">
    <style>
        html, body { font-size: 75%; }
    </style>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script src="http://rawgit.com/free-jqgrid/jqGrid/master/js/i18n/grid.locale-en.js"></script>
    <script>
        $.jgrid = $.jgrid || {};
        $.jgrid.no_legacy_api = true;
        $.jgrid.useJSON = true;
    </script>
    <script src="http://rawgit.com/free-jqgrid/jqGrid/master/js/jquery.jqgrid.src.js"></script>
    <script>
    //<![CDATA[
        /*global $ */
        /*jslint browser: true */
        $(function () {
            "use strict";
            var mydata = [
                    {id: "1", name: "Cash",        num: "100", debit: "400.00",  credit: "250.00",  balance: "150.00",   enbl: true,  level: "0", parent: "null", isLeaf: false, expanded: false, loaded: true},
                    {id: "2", name: "Cash 1",      num: "1",   debit: "300.00",  credit: "200.00",  balance: "100.00",   enbl: false, level: "1", parent: "1",    isLeaf: false, expanded: false, loaded: true},
                    {id: "3", name: "Sub Cash 1",  num: "1",   debit: "300.00",  credit: "200.00",  balance: "100.00",   enbl: true,  level: "2", parent: "2",    isLeaf: true,  expanded: false, loaded: true},
                    {id: "4", name: "Cash 2",      num: "2",   debit: "100.00",  credit: "50.00",   balance: "50.00",    enbl: false, level: "1", parent: "1",    isLeaf: true,  expanded: false, loaded: true},
                    {id: "5", name: "Bank\'s",     num: "200", debit: "1500.00", credit: "1000.00", balance: "500.00",   enbl: true,  level: "0", parent: "null", isLeaf: false, expanded: true,  loaded: true},
                    {id: "6", name: "Bank 1",      num: "1",   debit: "500.00",  credit: "0.00",    balance: "500.00",   enbl: false, level: "1", parent: "5",    isLeaf: true,  expanded: false, loaded: true},
                    {id: "7", name: "Bank 2",      num: "2",   debit: "1000.00", credit: "1000.00", balance: "0.00",     enbl: true,  level: "1", parent: "5",    isLeaf: true,  expanded: false, loaded: true},
                    {id: "8", name: "Fixed asset", num: "300", debit: "0.00",    credit: "1000.00", balance: "-1000.00", enbl: false, level: "0", parent: "null", isLeaf: true,  expanded: false, loaded: true}
                ],
                $grid = $("#tree_grid");

            $grid.jqGrid({
                data: mydata,
                colNames: ["Account", "Acc Num", "Debit", "Credit", "Balance", "Enabled"],
                colModel: [
                    {name: "name", width: 180},
                    {name: "num", template: "integer", align: "center"},
                    {name: "debit", template: "number"},
                    {name: "credit", template: "number"},
                    {name: "balance", template: "number"},
                    {name: "enbl", width: 60, template: "booleanCheckboxFa"}
                ],
                cmTemplate: { editable: true, width: 80, autoResizable: true },
                autoResizing: { compact: true },
                autoresizeOnLoad: true,
                iconSet: "fontAwesome",
                treeGrid: true,
                pager: true,
                //toppager: true,
                treeGridModel: "adjacency",
                navOptions: {add: false, del: false},
                searching: {multipleSearch: true, multipleGroup: true, closeOnEscape: true, showQuery: true, 
                closeAfterSearch: true},
                ExpandColumn: "name"
            }).jqGrid("navGrid")
              .jqGrid("setGroupHeaders", {
                useColSpanStyle: true,
                groupHeaders:[
                    {startColumnName: "name", numberOfColumns: 2, titleText: "<em>Account</em>"},
                    {startColumnName: "debit", numberOfColumns: 3, titleText: "Prices"}
                ]
            });
        });
    //]]>
    </script>
</head>
<body>
    <div style="margin:5px">
        <table id="tree_grid"></table>
    </div>
</body>
</html>
```

**Comment by OlegKi** [comment]
@dizzy0ny: I found the old post. free jqGrid should support all requirements (inclusive adding new items in TreeGrid). Could you load the current sources of free jqGrid from GitHub and verify that some problem still exist? Please close the issue if all problems are solved or describe the *current* problems which need be solved.

**Comment by OlegKi** [comment]
I close the issue. You can reopen it again if you find that the problem still not solved. I prefer that the person who reports a problem confirms that the fix work and he/she close the issue. Please think about closing the issues which you post the future. Best wishes!
