### ISSUE TITLE
jqgrid formediting checkOnUpdate

### ISSUE THREAD

**Issue by JincyRidge** [free-jqgrid/jqGrid#341]
hi,
Please check this jsfiddle http://jsfiddle.net/ehj0nyLu/15/ . I had given checkOnUpdate as true, but on the edit form, if you click on the navigation button from 2nd time that message box is asking whether to save data even though I had not made any changes. There is no issue when you click first time but i f you click again it is asking, Please check and let me know if I had done anything wrong.

jinct

**Comment by OlegKi** [comment]
Thank you for the bug report!

The problem exist if you use text of selects the same as the value of select. I mean that the value `'1'`  be used as the value of one option (see `'1':'0'`) and the text of another option (see `'21':'1'`). It's the old bug, which I fixed in the main code, but forgot to implement the same fix in case of usage navigation buttons of Add/Edit form.

I committed [the bug fix](https://github.com/free-jqgrid/jqGrid/commit/0f3f5cf84fd18b377a105ee9b1db9e42b89e130e) just now. Your demo uses the latest sources from GitHub and it works correctly now. Please refresh your jqGrid files and test new code in your environment. Don't forget to close the issue after verifying that the bug is fixed.

**Comment by JincyRidge** [comment]
I am using the jquery.jqGrid.min file in my application, so where will I get the updated file from to check if its solved or not?

**Comment by OlegKi** [comment]
I build full version of free jqGrid on every commit to GitHub. Thus you need just download [here](https://github.com/free-jqgrid/jqGrid). You need click on the button "Clone or download" and choose "Download ZIP". Alternatively you can clone the repository by git. One more option: you can load the files directly from GitHub using URLs, which starts with `https://rawgit.com/free-jqgrid/jqGrid/master/`, for example `https://rawgit.com/free-jqgrid/jqGrid/master/js/jquery.jqgrid.min.js`.

**Comment by JincyRidge** [comment]
OK I got it, but my issue in my orginal application still exists, eventhough i didnt made any changes it is asking if I need to save or not.  after opening the form when I click on next button its asking for saving.

**Comment by OlegKi** [comment]
Please verify that you works with new version: clean cache and so on. You can open jquery.jqgrid.min.js in your application and verify that it has comment with the text "... jqGrid 4.14.2-pre ... Date: 2017-06-07 ..."

**Comment by JincyRidge** [comment]
Yes I am using the new versions and I tried cleaning cache also but then also same issue persists. So I tried disabling the checkonUpdate property and try to create the desired behaviour through code.
so I tracked the changes in form and gave an alert for asking whether to save the change or not,. And then  onclickofpgbutton I entered the code for saving the current record. So I need to know how I will get the currently changed values. If I tried to take the values from controls directly it will be giving the new row values which is populated when we click on pgbuttons. Please advise.

**Comment by OlegKi** [comment]
I'm not sure that I can follow you. Could you create the demo with some test data, which I could use to reproduce the problem? I can find the reason of the problem and fix it only if I could debug the code, which reproduces the problem. Could you update your JSFiddle so that the problem still exist?

**Comment by JincyRidge** [comment]
Please see the demo http://jsfiddle.net/ehj0nyLu/20/ . In this If I click on 1st row and tried to change name from Adam to Jincy and then without saving I click on next arrow then I had write a code to ask whether to save or not and on click of ok I need to save it. So for that when we click on ok button I need to get the value Jincy, currently I will get the value Adam only on onclickPgButtons function using rowId. Hope you are clear now?

**Comment by OlegKi** [comment]
Sorry, but it seems to me that you make simple thing too complex. Try simplified code http://jsfiddle.net/OlegKi/ehj0nyLu/21/, which use just `checkOnUpdate: true` and some `editurl` (which should have the value `'<%= Url.Content( "~/Trend/AddPoint/")%>'` in your case). I used `formEditing` to set *default* option for form editing (for both Add and Edit forms). Now you can reproduce the test, which you describes. You open Edit form and change Adam to Jincy. If you click on "Submit" then the modified data will be posted to `editurl`. If you click on "next"/"prev" button then jqGrid will compare the current data in the form with the data, which was in the form before (it's the goal of `checkOnUpdate: true` property). It detects changing in the data and displays suggestion to save the data. If the user click "Save", then the modified data will be posted in exactly the same way like in case of clicking on "Submit" button. Finally the form will be filled with the next row of the grid.

You can use Developer Tools of Google/Internet Explorer to verify that the demo http://jsfiddle.net/OlegKi/ehj0nyLu/21/ really post the data like
```
name:Jincy 
company:1
oper:edit
id:1
```
to `editurl`. You need examine traffic in Network tab of Developer Tools.

**Comment by JincyRidge** [comment]
Sorry to bother you but as I said in one of my previous posts my issue, in my orginal application I am creating, the checkonUpdate is working even if there is no  change happened in the form. I had a detailed check and could not find out the issue that is why I had gone with the other method.

**Comment by OlegKi** [comment]
The problem, which you reported, was the bug in, which I fixed (see https://github.com/free-jqgrid/jqGrid/commit/0f3f5cf84fd18b377a105ee9b1db9e42b89e130e above). Thus now `checkonUpdate: true` option should work without any problem. It should display the dialog, where one ask to save, **only if the user really changed the data in the form**. You can verify it yourself.

**Comment by JincyRidge** [comment]
yes that I understood but somehow after using all the latest versions also it is not working for me and then only I moved with my way of doing that. So if you know how I can access that values then it will be great.

**Comment by OlegKi** [comment]
We come now back to my first comment. Please test the functionality of `checkonUpdate: true` with the current code of free jqGrid. It should work correctly now.

If you say that it works incorrectly (sometimes), then I can help to fix the problem only if you provide the demo, which reproduce the problem. The demo should demonstrate the bug in functionality of `checkonUpdate: true` and not be your custom code, which don't use `checkonUpdate: true` at all.

**Comment by OlegKi** [comment]
@JincyRidge I didn't receive any additional information from you during long time. The bug, which you reported initially should be fixed as 8 Jun 2017 (see [here](https://github.com/free-jqgrid/jqGrid/commit/0f3f5cf84fd18b377a105ee9b1db9e42b89e130e)). I'm closing the issue now. If you will find some new information concerned the subject you can reopen the issue or post new issue.
